
import { ClientProviders } from '@/lib/clientProviders'

require('@solana/wallet-adapter-react-ui/styles.css')
require('./globals.css')


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  )
}
